Algoritmo "combustivelGasto"
//
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/11/2022
Var
// Seção de Declarações das variáveis 

distancia: inteiro
combustivel: inteiro
total: inteiro

Inicio

// Seção de Comandos, procedimento, funções, operadores, etc... 

distancia <- 2000
combustivel <- 10
total <- (distancia*combustivel)

escreva (total)

Fimalgoritmo