Algoritmo "IMC"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/11/2022
Var
// Seção de Declarações das variáveis 

altura: real
peso: inteiro
IMC: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

peso <- 80
altura <- 3.24
IMC <- (peso/altura)

escreva (IMC)

Fimalgoritmo