Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/11/2022


Var
// Seção de Declarações das variáveis 
//mostrar as operacoes matemativas basicas com os numeros
a,b : inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

a <- 10
b <- 5

escreva (a+b)
escreva (a-b)
escreva (a*b)
escreva (a/b)



Fimalgoritmo